apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    spec:
      containers:
        - name: pinger
          image: pkbhowmick/mongo-ping:v0.0.1
          args:
            - --svc-url=mongodb://mongodb-dev.default.svc.cluster.local
      restartPolicy: Never
  backoffLimit: 2